package:
    type:           library
    name:           omnipay-epayservice
    namespace:      Omnipay\ePayService
    headline:       'Omnipay: ePayService'
    title:          ePayService driver for the Omnipay PHP payment processing library
    license:        MIT
    keywords:       php, omnipay, epayservice, merchant, payment
    year:           2015
    description:    |
        [Omnipay](https://github.com/omnipay/omnipay) is a framework agnostic, multi-gateway payment
        processing library for PHP 5.3+.
        This package implements [ePayService](http://epayservices.com/) support for Omnipay.

require:
    hiqdev/hidev-php:    "*"
    hiqdev/hidev-vendor: "*"
